### ISSUE TITLE
Empty raster tiles throw 404 error

### ISSUE THREAD

**Issue by jaskiratr** [UrbanSystemsLab/raster-to-mbtiles#2]
mapbox-gl.js?d5ed:503 
GET https://a.tiles.mapbox.com/v4/****/11/648/916@2x.webp?access_token=***** 404 (Not Found)

**Comment by auchers** [comment]
looking through [this issue](https://github.com/mapbox/mapbox-gl-js/issues/1800#issuecomment-254435323) -- looks like most of the discussion is regarding how to suppress the errors, rather than how to build a tileset that won't cause them.

**Comment by auchers** [comment]
found [this issue](https://github.com/mapbox/mapbox-gl-js/issues/1800) related to ours - though most of the talk there seems to be around suppression of the error, not remaking the tileset

**Comment by jaskiratr** [comment]
Seems like a browser issue. I guess, Mapbox doesn't throw a 404. 

https://github.com/mapbox/mapbox-gl-js/issues/5093
